### DISCUSSION TITLE
Catalog Server doesn't show the catalogs of sub EDCs

### DISCUSSION THREAD

**Discussion by marctuerke** [eclipse-tractusx/tractusx-edc#1697] [General]
I created a federated catalog and want to request the catalog from the catalog server, but the dataset inside the catalog asset is empty.

```HTTP
POST https://control.consumer-edc.c-27d7c36.kyma.ondemand.com/management/v3/catalog/request HTTP/1.1

{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  },
  "@type": "CatalogRequest",
  "counterPartyId": "{BPN}",
  "counterPartyAddress": "https://catalog-server.c-27d7c36.kyma.ondemand.com/api/v1/dsp",
  "protocol": "dataspace-protocol-http",
  "querySpec": {
    "@type": "QuerySpec"
  }
}
```

```JSON
{
  "@id": "64a61292-e98f-488e-81b0-c0c29050e9ab",
  "@type": "dcat:Catalog",
  "dcat:dataset": {
    "@id": "provider-edc-1",
    "@type": "dcat:Catalog",
    "dcat:dataset": [],
    ...
}
```

I created the catalog asset as follows:

```HTTP
POST https://control.catalog-server.c-27d7c36.kyma.ondemand.com/management/v3/assets HTTP/1.1
Content-Type: application/json

{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "cx-common": "https://w3id.org/catenax/ontology/common#",
    "cx-taxo": "https://w3id.org/catenax/taxonomy#",
    "dct": "http://purl.org/dc/terms/"
  },
  "@id": "provider-edc-1",
  "@type": "CatalogAsset",
  "properties": {
    "description": "This is a linked asset that points to another EDC's catalog.",
    "isCatalog": true
  },
  "dataAddress": {
    "@type": "DataAddress",
    "type": "HttpData",
    "baseUrl": "https://provider-edc-1.c-27d7c36.kyma.ondemand.com/api/v1/dsp"
  }
}
```

The Sub-EDC has an entry in the target nodes directory (implemented via a config map) and are mounted in the catalog server:

```JSON
[
    {
      "name": "provider-edc-1",
      "url": "https://provider-edc-1.c-27d7c36.kyma.ondemand.com/api/v1/dsp",
      "id": "{BPN}",
      "supportedProtocols": "dataspace-protocol-http"
    }
]
```

```YAML
controlplane:
  ...
  volumeMounts:
      - name: "config-volume"
        mountPath: "/etc/config"
  volumes: 
    - name: "config-volume"
      configMap:
        name: targetnodes
  ...
```

The Sub-EDC contains contracts definitions which are accessible by the catalog server and the consumer edc.

I also can't access the Catalog Query endpoint. 

```HTTP
POST https://control.catalog-server.c-27d7c36.kyma.ondemand.com/catalog/v1alpha/catalog/query  HTTP/1.1
Content-Type: application/json

{
    "@context": {
        "edc": "https://w3id.org/edc/v0.0.1/ns/"
    },
    "@type": "QuerySpec"
}
```

It throws the HTTP Error 503 Service unavailable, although I exposed it via an Ingress. 

```YAML
controlplane:
  ...
  ingresses:
    ...
    - enabled: true
          # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
          hostname: "control.catalog-server.c-27d7c36.kyma.ondemand.com"
          # -- Additional ingress annotations to add
          annotations: {}
          # -- EDC endpoints exposed by this ingress resource
          endpoints:
            - management
            - control
            - catalog
          ...
```

I'd love some hints with regards to fixing this.
