### DISCUSSION TITLE
Controlplane Service doesn't expose the catalog endpoint (/catalog, Port 8085)

### DISCUSSION THREAD

**Discussion by marctuerke** [eclipse-tractusx/tractusx-edc#1711] [Ideas]
The control plane service does not expose the catalog endpoint. In order to expose the catalog endpoint (/catalog, Port 8085) via an Ingress, it was necessary to add the catalog endpoint to the service manually.

My controlplane service now looks like this:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "txdc.fullname" . }}-controlplane
  namespace: {{ .Release.Namespace }}
  {{- with .Values.controlplane.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "txdc.controlplane.labels" . | nindent 4 }}
    {{- with .Values.controlplane.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.controlplane.service.type }}
  ports:
    - port: {{ .Values.controlplane.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.controlplane.endpoints.control.port }}
      targetPort: control
      protocol: TCP
      name: control
    - port: {{ .Values.controlplane.endpoints.management.port }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.controlplane.endpoints.protocol.port }}
      targetPort: protocol
      protocol: TCP
      name: protocol
    - port: {{ .Values.controlplane.endpoints.catalog.port }}
      targetPort: catalog
      protocol: TCP
      name: catalog
    - port: {{ .Values.controlplane.endpoints.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "txdc.controlplane.selectorLabels" . | nindent 4 }}
```
