### DISCUSSION TITLE
Questions about EDC connector vault configuration

### DISCUSSION THREAD

**Discussion by lesile231** [eclipse-tractusx/tractusx-edc#2054] [Q&A] [answered]
HI, I hope to you all doing well!

Our company is planning to receive consulting from CofinityX. We're currently trying to connect the components from https://github.com/eclipse-tractusx/digital-product-pass, but we keep getting an error where the connector can't find the vault. and I came here because we're using repository: "tractusx/edc-controlplane-postgresql-hashicorp-vault" in our connector configuration.

Specifically, the control-plane logs show: 
```DEBUG 2025-06-25T06:43:43.14231051 [Hashicorp Vault] Failed to resolve secret 'secret/data/client-secret': [Failed to get secret with status 404]```. 
The connector configuration and vault values seem to be set up correctly, but we suspect it might be due to the vault version. I'm posting this question and will provide the necessary information below.

In this case, Could you give me some tips to resolve this error here?

*  DPP-backend log capture *
<img width="844" alt="Screenshot 2025-06-25 at 16 56 55" src="https://github.com/user-attachments/assets/15ae1dd8-67d4-4d1b-8a66-442daa6a4985" />
*  DPP-backend log capture *

*  Connector (control-plane) log capture *
<img width="835" alt="Screenshot 2025-06-25 at 16 56 02" src="https://github.com/user-attachments/assets/1bea2b69-abd1-4345-bbf0-bca332493ae7" />
*  Connector (control-plane) log capture *

* Vault's secret capture*
<img width="1674" alt="Screenshot 2025-06-25 at 17 24 05" src="https://github.com/user-attachments/assets/698ae6e0-99f4-428e-bec4-66c164d49204" />
* Vault's secret capture*

 * Connector's yaml *
```
tractusx-connector:
  enabled: true
  install:
    daps: false
    postgresql: false
    vault: true
  fullnameOverride: "dpp-edc-consumer"
  nameOverride: ""
  # -- Existing image pull secret to use to [obtain the container image from private registries](https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry)
  imagePullSecrets: []
  customLabels: {}

    
  participant:
    id: "did:web:localhost%3A7093"

  iatp:
    # Decentralized IDentifier
    id: "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1"
    trustedIssuers: # array [] that needs to be expand but likely like (sorry unconfirmed on how this is done, as I also would need to check)
      - "did:web:dim-static-prod.dis-cloud-prod.cfapps.eu10-004.hana.ondemand.com:dim-hosted:2f45795c-d6cc-4038-96c9-63cedc0cd266:holder-iatp"
    sts:
      dim:
        url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal"
      oauth:
        token_url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal/token" 
        client:
          id: "Cl13-CX-Battery"
          secret_alias: "secret/data/client-secret"

  # -- Add custom ca certificates to the truststore
  customCaCerts: {}

  controlplane:
    enabled: true
    image:
      # -- Which derivate of the control plane to use. when left empty the deployment will select the correct image automatically
      repository: "tractusx/edc-controlplane-postgresql-hashicorp-vault"
      # -- [Kubernetes image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy) to use
      pullPolicy: IfNotPresent
    initContainers: []
    debug:
      enabled: true
      port: 1044
      suspendOnStart: false
    livenessProbe:
      # -- Whether to enable kubernetes [liveness-probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
      enabled: true
      # -- seconds to wait before performing the first liveness check
      initialDelaySeconds: 30
      # -- this fields specifies that kubernetes should perform a liveness check every 10 seconds
      periodSeconds: 10
      # -- number of seconds after which the probe times out
      timeoutSeconds: 5
      # -- when a probe fails kubernetes will try 6 times before giving up
      failureThreshold: 6
      # -- number of consecutive successes for the probe to be considered successful after having failed
      successThreshold: 1
    readinessProbe:
      # -- Whether to enable kubernetes [readiness-probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
      enabled: true
      # -- seconds to wait before performing the first readiness check
      initialDelaySeconds: 30
      # -- this fields specifies that kubernetes should perform a liveness check every 10 seconds
      periodSeconds: 10
      # -- number of seconds after which the probe times out
      timeoutSeconds: 5
      # -- when a probe fails kubernetes will try 6 times before giving up
      failureThreshold: 6
      # -- number of consecutive successes for the probe to be considered successful after having failed
      successThreshold: 1
    # -- endpoints of the control plane
    endpoints:
      # -- default api for health checks, should not be added to any ingress
      default:
        # -- port for incoming api calls
        port: 8080
        # -- path for incoming api calls
        path: /consumer/api
      # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
      management:
        # -- port for incoming api calls
        port: 8081
        # -- path for incoming api calls
        path: /consumer/management
        # -- authentication key, must be attached to each 'X-Api-Key' request header
        authKey: "password"
      # -- control api, used for internal control calls. can be added to the internal ingress, but should probably not
      control:
        # -- port for incoming api calls
        port: 8083
        # -- path for incoming api calls
        path: /consumer/control
      # -- ids api, used for inter connector communication and must be internet facing
      protocol:
        # -- port for incoming api calls
        port: 8084
        # -- path for incoming api calls
        path: /consumer/api/v1/dsp
      # -- metrics api, used for application metrics, must not be internet facing
      metrics:
        # -- port for incoming api calls
        port: 9090
        # -- path for incoming api calls
        path: /consumer/metrics

    bdrs:
      # time that a cached BPN/DID resolution map is valid in seconds, default is 10 min
      cache_validity_seconds: 600
      server:
        # URL of the BPN/DID Resolution Service - required:
        url: "https://bpn-did-resolution-service.int.catena-x.net/api/directory"

  vault:
    fullnameOverride: "vault"
    injector:
      enabled: false
    server:
      dev:
        enabled: true
        devRootToken: "root"
      # Must be the same certificate that is configured in section 'daps'
      postStart:    # must be set externally!
    hashicorp:
      url: "http://vault:8200"
      token: "root"
      timeout: 30
      healthCheck:
        enabled: true
        standbyOk: true
      paths:
        secret:  ""
        health: /v1/sys/health
```
 * Connector's yaml *

Thank you for your time !! Always thank you!

**Comment by FaheemBhatti** [comment]
Hi there 👋,

Thanks for sharing your configuration. I’ve reviewed the values file and noticed a couple of potential issues that might be causing the problem. Based on that, here are a few recommended changes to align with best practices and ensure compatibility:

✅ Suggested Changes:
🔹 Update your iatp section with the following:
```
iatp:
  # Decentralized Identifier
  id: "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1"
  trustedIssuers: 
    # This array may require extension; syntax is assumed and may need verification
    - "did:web:dim-static-prod.dis-cloud-prod.cfapps.eu10-004.hana.ondemand.com:dim-hosted:2f45795c-d6cc-4038-96c9-63cedc0cd266:holder-iatp"
  sts:
    dim:
      url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal"
    oauth:
      token_url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal/token"
      client:
        id: "Cl13-CX-Battery"
        secret_alias: "client-secret"

```
🔹 Replace your vault section with this updated version:

```
vault:
  injector:
    enabled: false
  server:
    dev:
      enabled: false
      devRootToken: ""
    postStart: null
  hashicorp:
    url: "http://{{ .Release.Name }}-vault:8200"
    token: "your-top-secret"
    timeout: 30
    healthCheck:
      enabled: true
      standbyOk: true
    paths:
      secret: "/v1/secret"
      health: "/v1/sys/health"
```

🔹 Important:
In your Vault configuration, for storing the secrets, be sure to change the key name from **value** to **content**.

Please apply these changes and let me know if this resolves the issue. If you run into anything else or need further clarification, I’m happy to help.

Happy data transferring in D-Space! 🚀

**Reply by lesile231** [reply]
First of all, thank you soo much for your reply. I have been struggling with this issue for 2 weeks. 

Unfortunately, I haven't solved this problem yet. I applied your suggestion and got a different error ("401 unauthorized"). I think this error means I have to get real authentication values from somewhere like IATP ("https://dis-integration-service-prod.eu10.dim.cloud.sap/"). Is there any process for getting these values properly? 

-- ERROR LOG
SEVERE 2025-07-05T16:53:35.476172294 HTTP client exception caught for request [POST, https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal/token]
org.eclipse.edc.http.spi.EdcHttpClientException: Server response to [POST, https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal/token] was not one of [200] but was 401: Unauthorized

<img width="794" alt="Screenshot 2025-07-05 at 23 38 33" src="https://github.com/user-attachments/assets/1218aca1-94d4-462d-b19a-db1ca2ddb49f" />

OR 
My company has registered to Cofinity-X's beta environment (https://myportal.cofinity-x.com/, https://centralidp.beta.cofinity-x.com/auth/realms/CX-Central), so we have 'BPN' and tech user's client ID and client secret (AUTH TYPE is SECRET). Could I use these values in my values.yaml?

+ 
Ultimately, my goal is to deploy a Digital Product Passport for testing purposes and test it locally. So, I've deployed the pods as shown below, and the dpp-frontend is running well, but I'm stuck with the authentication error mentioned above in the dpp-backend <-> EDC integration. I think this is probably the final step, but is there anywhere I can get help or find reference sources for this?

<img width="752" alt="Screenshot 2025-07-06 at 00 38 37" src="https://github.com/user-attachments/assets/85d6bdd2-fce8-4e44-b70e-0c62a3be0d42" />

**Reply by FaheemBhatti** [reply]
Thank you for implementing the suggested changes. It appears that we have successfully resolved the 404 Not Found error originating from the Vault, which is a positive step forward.

Now, let's focus on addressing the current issue:

Verify Client Credentials
Please ensure that the client.id and client.secret values are correct. A 401 Unauthorized error typically indicates that these credentials are either incorrect.

```
   oauth:
        token_url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal/token" 
        client:
          id: "Cl13-CX-Battery"
          secret_alias: "client-secret"
```

Check BDRS Server Availability
Confirm that the BDRS server is up and running. Additionally, verify that the URLs being used are accurate and accessible.

Validate Identities
Make sure that the identities are being provided by a recognized and trusted issuer wallet.

**Reply by lesile231** [reply]
Thank you for your time!

You are absolutely right.

I was trying to run BDRS and DIM-WALLET locally, but I didn't understand it well enough.

So, I tried a different approach using the beta or integration server from Cofinity-X. Is there any way to generate the proper client ID and client secret?

Or would it be better to run BDRS and DIM-WALLET locally for testing? (It looks like I also need to run the portal backend as well)


I really appreciate all your help so far. I felt stuck and hitting a wall, but having your support has been incredibly helpful.

**Reply by FaheemBhatti** [reply]
There needs to be a known issuer from whom we can get the credentials and the identities. Further, I can only help after getting to know the BDRS configurations and how the entries are added. Also I tried resolving your DID. can you please also have a look at here whether there is all that you need inside. 

Also, we can generate a one-on-one session between us, to further check what's going wrong.

Thank you

```
{
  "id": "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1",
  "service": [
    {
      "id": "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1#CredentialService",
      "type": "CredentialService",
      "serviceEndpoint": "https://dis-agent-prod.eu10.dim.cloud.sap/api/v1.0.0/iatp"
    }
  ],
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "keyAgreement": [],
  "authentication": [
    "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1#keys-38b98f3e-26a1-4b43-89d1-2763bfb405d6"
  ],
  "assertionMethod": [],
  "verificationMethod": [
    {
      "id": "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1#keys-38b98f3e-26a1-4b43-89d1-2763bfb405d6",
      "type": "JsonWebKey2020",
      "controller": "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1",
      "publicKeyJwk": {
        "x": "LZfmJcYqXiIJJ0j2vVtIWDF24-WrrtcsK0yGVNY-UVw",
        "y": "BbZIoxO2t20094kambaPC9xKjYB7QomTrEKWrJ2fxQo",
        "crv": "secp256k1",
        "kty": "EC"
      }
    }
  ]
}

```

**Reply by arnoweiss** [reply]
1. Locally: You have full control. That's good and bad. For wallets, you'd have to deploy and integrate with a mock for the wallet APIs called [dim-wallet-stub](https://github.com/eclipse-tractusx/ssi-dim-wallet-stub). Same for the BDRS. 
2. To integrate with productive wallets, you will need access to the client credentials of a particular wallet tenant. If your organization has a landscape for testing (like cofinity beta), you should be able to obtain the wallet credentials from someone in your org.

**Comment by lesile231** [comment]
Thanks for all your help!

I was trying to test based on your guidance, but it still failed.

I will write down the logs and my environment values precisely.

After running EDC, I executed export VAULT_ADDR="http://127.0.0.1:8200" && export VAULT_TOKEN='root' && vault kv put secret/client-secret content="J36isa8OXAtaiwYIXP8fls6q1l3jxCrx" to insert client's secret ('BPNL00000003AYRE') into Vault.

Now, it seems to be trying to request to 'portal-backend.int.catena-x.net' which was extracted from the DID, but a timeout occurs. Even if the connection is made, it probably won't work because the ID seems wrong. I think I need to properly configure the values that can actually be used in this setup


******** LOGS ********
 - EDC ERROR LOG
<img width="954" alt="edc-log" src="https://github.com/user-attachments/assets/bf6838b5-9254-4095-a9c7-1cd722275592" />

 - DPP-BACKEND ERROR LOG
<img width="936" alt="dpp-backend-log" src="https://github.com/user-attachments/assets/126b3b76-5afd-49a7-849b-b45dc66812a9" />

 - DIM-WALLET LOG (DID Related)
<img width="965" alt="dim-wallet-log" src="https://github.com/user-attachments/assets/6d633841-8895-474f-80b6-ac24eb1ecf78" />
 token text: eyJraWQiOiJkaWQ6d2ViOmxvY2FsaG9zdDpCUE5MMDAwMDAwMDNBWVJFIzVlOWYwOTU3LTYxMjktMzNlZi1iODU1LTZmMzliMWM4ZGMwNyIsInR5cCI6IkpXVCIsImFsZyI6IkVTMjU2SyJ9.eyJhdWQiOiJkaWQ6d2ViOmxvY2FsaG9zdDpCUE5MMDAwMDAwMDAwMDAwIiwic3ViIjoiZGlkOndlYjpsb2NhbGhvc3Q6QlBOTDAwMDAwMDAzQVlSRSIsImJwbiI6IkJQTkwwMDAwMDAwMDAwMDAiLCJzY29wZSI6InJlYWQiLCJpc3MiOiJkaWQ6d2ViOmxvY2FsaG9zdDpCUE5MMDAwMDAwMDNBWVJFIiwiZXhwIjoxNzUxODkwNzkxLCJpYXQiOjE3NTE4OTA0OTEsIm5vbmNlIjoiNjIzN2ZlOTctOTg4NC00YmJjLWJjNzEtY2RiNmUyMGRiNjcxIiwianRpIjoiZmY0M2VlMWUtNWQ1Yy00ODk1LWJjZmYtYzUwM2Q1YTllMjFkIiwidG9rZW4iOiJleUpyYVdRaU9pSmthV1E2ZDJWaU9teHZZMkZzYUc5emREcENVRTVNTURBd01EQXdNRE5CV1ZKRkl6VmxPV1l3T1RVM0xUWXhNamt0TXpObFppMWlPRFUxTFRabU16bGlNV000WkdNd055SXNJblI1Y0NJNklrcFhWQ0lzSW1Gc1p5STZJa1ZUTWpVMlN5SjkuZXlKaGRXUWlPaUprYVdRNmQyVmlPbXh2WTJGc2FHOXpkRHBDVUU1TU1EQXdNREF3TURBd01EQXdJaXdpYzNWaUlqb2laR2xrT25kbFlqcHNiMk5oYkdodmMzUTZRbEJPVERBd01EQXdNREF6UVZsU1JTSXNJbUp3YmlJNklrSlFUa3d3TURBd01EQXdNMEZaVWtVaUxDSnpZMjl3WlNJNkluSmxZV1FpTENKcGMzTWlPaUprYVdRNmQyVmlPbXh2WTJGc2FHOXpkRHBDVUU1TU1EQXdNREF3TUROQldWSkZJaXdpWTNKbFpHVnVkR2xoYkZSNWNHVnpJanBiSWsxbGJXSmxjbk5vYVhCRGNtVmtaVzUwYVdGc0lsMHNJbVY0Y0NJNk1UYzFNVGc1TURjNU1Td2lZMjl1YzNWdFpYSkVhV1FpT2lKa2FXUTZkMlZpT25OemFTMWthVzB0ZDJGc2JHVjBMWE5sY25acFkyVXVkMkZzYkdWMExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc09rSlFUa3d3TURBd01EQXdNREF3TURBaUxDSnBZWFFpT2pFM05URTRPVEEwT1RFc0luQnliM1pwWkdWeVJHbGtJam9pWkdsa09uZGxZanB6YzJrdFpHbHRMWGRoYkd4bGRDMXpaWEoyYVdObExuZGhiR3hsZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRwQ1VFNU1NREF3TURBd01EQXdNREF3SW4wLllRNmg5d1ZWV0I5dzJxeHdGUUY1b0Z6a2RTeVZFenNMeDhWT3BiRGJtZW1TTDlLV2R5b25Dazc0N01HemRYNFpDUUtTWVhCTjRJb3hsTDN2V0x6S3NRIn0.X6PBaB5LpRj8LcfMg7bfecVCIUSBguOA7v7mXq6HX06nvWLR19N8n4UvwMdtT4jpwaim_tyineg1w_MXs8yNSg

******** LOGS ********


I draw a simple figure of envs for your understanding!
<img width="939" alt="Screenshot 2025-07-07 at 23 03 26" src="https://github.com/user-attachments/assets/0a07dcdf-bed0-457f-8bc9-03cc117533e2" />

******** ENV ********
 1) EDC
```
  participant:
    id: "did:web:localhost%3A7093"

  iatp:
    # Decentralized IDentifier
    id: "did:web:portal-backend.int.catena-x.net:api:administration:staticdata:did:BPNL000000000FV1"
    trustedIssuers: # array [] that needs to be expand but likely like (sorry unconfirmed on how this is done, as I also would need to check)
      - "did:web:dim-static-prod.dis-cloud-prod.cfapps.eu10-004.hana.ondemand.com:dim-hosted:2f45795c-d6cc-4038-96c9-63cedc0cd266:holder-iatp"
    sts:
      dim:
        #url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal"
        url: "http://ssi-dim-wallet-service.wallet.svc.cluster.local:8080/api/sts"
      oauth:
        #token_url: "https://dis-integration-service-prod.eu10.dim.cloud.sap/api/v2.0.0/iatp/catena-x-portal/token"
        token_url: "http://ssi-dim-wallet-service.wallet.svc.cluster.local:8080/oauth/token"
        client:
          #id: "BPNL00000003AYRE"
          # BPN
          id: "BPNL00000003AYRE"
          secret_alias: "client-secret"
```

 2) DPP-BACKEND
```
  auth:
    #identityProvider: "http://host.minikube.internal:8088"
    identityProvider: "http://localhost:8088"
    clientId: "Cl13-CX-Battery"
    clientSecret: "DK9P2oKyIqa6M9QBQEcenKSMrFyJPjyG"  # 일관성을 위해 추가됨
    realm: "CX-Central"
    onLoad: "login-required"
    bpnCheck: false
    roleCheck: false
```

 3) DIM-WALLET
```
  environment: "local"
  # -- Operator BPN
  baseWalletBpn: "BPNL000000000000"
  # -- List of BPNs for which wallets will be seeded on application startup
  seeding:
    #bpnList: ""
    bpnList: "BPNL00000003AZQP,BPNL00000003AYRE"
  # -- Did document host, this will be part of did String i.e., did:web:<didHost>
  didHost: "localhost"
  # -- Wallet stub server URL. This will pe part of the presentation query API in the did document
  stubUrl: "http://localhost"
  # -- Default status list VC id
  statusListVcId: "8a6c7486-1e1f-4555-bdd2-1a178182651e"
  # -- Token expiry time in seconds
  tokenExpiryTime: "5"
  portal:
    # -- Wait for given seconds before pushing data to portal backend after wallet creation
    waitTime: "60"
    # -- Portal backend application host
    host: "http://localhost"

    # -- Keycloak client_id and client_secret. We will create an access token and using this we access portal backend APIs
    #clientId: "client_id"
    #clientSecret: "client_secret"
    clientId: "BPNL00000003AYRE"
    clientSecret: "DK9P2oKyIqa6M9QBQEcenKSMrFyJPjyG"
  keycloak:
    # -- Keycloak realm name
    realm: "CX-Central"
    # -- keycloak host
    #authServerUrl: "http://localhost:28080/auth"
    authServerUrl: "http://localhost:8088/realms"
```

 4) BDRS (https://github.com/eclipse-tractusx/bpn-did-resolution-service) use this repository without changes.

******** ENV ********

As I understand it, I need to add BPN or DID into BDRS before testing, or some advance action is required.
And how can I set up a one-on-one session between us? Is there any request I need to make?

Thanks to your time, I can't express enough how grateful I felt!!
