### DISCUSSION TITLE
Get rid of manual CHANGELOG

### DISCUSSION THREAD

**Discussion by paullatzelsperger** [eclipse-tractusx/tractusx-edc#253] [Ideas]
## WHAT

Having to manually maintain a `CHANGELOG` file is tedious, error prone and almost always people are forgetting something.

My proposal would thus be the following:
- enforce conventional commits (see snippet below)
- reviewers must take care that good and understandable commit messages are used
- only use the Changelog, that is automatically generated by GH releases
- delete/archive the `CHANGELOG.md` file

## WHY

The upside would be a higher degree of automation, and with it, a smaller chance for human error.
Conventional commits are not less intuitive for the human reader (that is who they are intended for after all), and the benefits of automation massively outweigh the less "prosaic" nature.

## Enforcing conventional commits
can be done with this GH Action (taken from EDC):
```yaml
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+((,|\/|\\)?\s?\w+)+\))?!?: [\S ]{1,80}[^\.]$'
          allowed_prefixes: 'build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test'
          prefix_case_sensitive: true
```
