### ISSUE TITLE
In Memory Helm chart misses the service definition for the public data plane

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/tractusx-edc#1011]
## Describe the bug

A Proxy Pull flow can't be performed with the helm chart. When used with ingress (also configuring the ingress to be internet facing), then the public/api endpoint returns a 503

### To Reproduce

_Steps to reproduce the behavior:_

1. Configure your ingress as follows (additionally configure your ssi / miw config as needed)
````
  ingresses:
    ## Public / Internet facing Ingress
    - enabled: true
      # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
      hostname: "your-hostname"
      # -- Additional ingress annotations to add
      annotations: {}
      # -- EDC endpoints exposed by this ingress resource
      endpoints:
        - protocol
        - management
        - control
        - public
        - proxy
      # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
      className: "nginx"
      # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
      tls:
        # -- Enables TLS on the ingress resource
        enabled: true
        # -- If present overwrites the default secret name
        secretName: "secret-name"
      ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
      certManager:
        # -- If preset enables certificate generation via cert-manager namespace scoped issuer
        issuer: ""
        # -- If preset enables certificate generation via cert-manager cluster-wide issuer
        clusterIssuer: ""

````
2. install the [tractus-x in memory connector helm chart](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/charts/tractusx-connector-memory/values.yaml) with the ingress definition.
3. Perform a post without auth against https:<your-hostname>/api/public -> should return 403 but results in 503

### Expected behavior

If no auth is given, 403 should happen.

### Screenshots/Error Messages

_If applicable, add screenshots and/or error messages to help explain your problem._

## Context Information

_Add any other context or information about the problem here._

- Used version: Tag 0.5.3
- OS: Linux Ubuntu 22.4.4 LTS
- Docker Version: don't know, argo cd
- `java --version`: don't know

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

Problem is related to template which does not provide a service definition for public port. Got it running via live manifest update on argo, but now run into a 404 problem again because /validation/token can't be found
