### ISSUE TITLE
Setup and implement publishing Docker images to DockerHub

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#164]
## Description
When publishing Docker images to GitHub packages in an Eclipse-managed Github repository, they are automatically set to `private`. This is an org-wide setting and cannot be changed.

Thus, we must publish our docker images to DockerHub.

## Requirements
- image namespace and name must be defined as env variables
- we must use org-provided credentials to log into Dockerhub:
  ```yaml
   - name: DockerHub login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
  ```
- the `README.md` file must contain a Notice section, similar to the [IRS example](https://github.com/eclipse-tractusx/item-relationship-service#notice-for-docker-image)
- the description (by default: `README.md`) must get published to DockerHub as well using a GH Actions:
  ```yaml
    - name: Update Docker Hub description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
  ```

## Implementation proposal

- leave publishing to GH Packages in for now, just to be safe
- Extract building and pushing docker images to a separate GH workflow `publish-docker.yaml`
- `publish-docker.yaml` runs only on pushes to `develop` and `main` and only if the Dockerhub credentials are present (prevents runs on forks)
