### ISSUE TITLE
CI: extract the checkout and setup-java action into a re-usable action

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#231]
## WHAT
The `checkout` and `setup-java` actions should be extracted into a re-usable composite action.

In many workflow files we find multiple blocks of

```yaml
      # Set-Up
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
```

which not only contains a small bug ("Set up JDK 11" instead of "17"), but it is also repetitive.

## WHY
avoid duplication, create consistency, one place to maintain the code, e.g. for version upgrades
