### ISSUE TITLE
Add "add-to-project" action/workflow to add features/bugs to a project/board

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractusx-edc#263]
### Discussed in https://github.com/eclipse-tractusx/tractusx-edc/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **stephanbcbauer** April  5, 2023</sup>
**Current situation**

Since more and more work is being done in Github and issues are also being created, it is currently difficult to keep track of everything. Priorities can also not be seen immediately.

**Proposal**

Two projects should first be created under tractusx-edc. The project template Team backlog is suitable for this. 

One board is for features (enhancement) and one for bugs. I think the separation is very good because of the clarity. With the template, the boards each have the columns `New`, `Backlog`, `Ready`, `In Progress`, `In Review` and `Done`. The status helps to keep the overview in the daily meeting.

New issues should be automatically entered into the corresponding board. It is recommended to use a Github action for this:

For example:

```yaml
name: Add to Project

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add defect
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/eclipse-tractusx/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug
      
      - name: Add feature
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/eclipse-tractusx/projects/5
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: enhancement
```

With these actions, new features and bugs are automatically added to the related boards. It might be the case, that there is a need to change the workflow under board settings to set the first column correctly…

If this works, I would like to do the same with PRs.

@stefan-ettl What do you think from the PO perspective?</div>
