### ISSUE TITLE
Running the chart 0.3.3 with controlplane.ingress.enabled=true produces invalid helm chart

### ISSUE THREAD

**Issue by jerzy-wachowiak** [eclipse-tractusx/tractusx-edc#348]
## Bug description
Running the chart 0.3.3 with controlplane.ingress.enabled=true produces invalid helm chart
```
spec:
  rules:
    - host: edc-control.local
      http:
        paths:
---
# Source: tractusx-connector/templates/configmap-controlplane.yaml
```

## Bug fixing
The solution is a renaming of ids to protocol
```
  # -- ids api, used for inter connector communication and must be internet facing
    protocol:
      # -- port for incoming api calls
      port: 8084
      # -- path for incoming api calls
      path: /api/v1/ids
```

From: 
```
  ingresses:
    ## Public / Internet facing Ingress
    - enabled: true
      # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
      hostname: "edc-control.local"
      # -- Additional ingress annotations to add
      annotations: {}
      # -- EDC endpoints exposed by this ingress resource
      endpoints:
        - ids
```
To:
```
 ingresses:
    ## Public / Internet facing Ingress
    - enabled: true
      # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
      hostname: "edc-control.local"
      # -- Additional ingress annotations to add
      annotations: {}
      # -- EDC endpoints exposed by this ingress resource
      endpoints:
        - protocol
```
